### ISSUE TITLE
发布 npm start

### ISSUE THREAD

**Issue by pauloved** [fyl080801/egg-vite-vue3#3]
静态文件访问不到，找不到原因 ，能看看吗
![image](https://user-images.githubusercontent.com/20351530/176634592-b37b3b19-ab39-492f-bcce-e48e419d36de.png)

**Comment by pauloved** [comment]
静态资源设置的问题

**Comment by fyl080801** [comment]
> 静态文件访问不到，找不到原因 ，能看看吗 ![image](https://user-images.githubusercontent.com/20351530/176634592-b37b3b19-ab39-492f-bcce-e48e419d36de.png)

什么操作出现的问题？

**Comment by fyl080801** [comment]
> 静态文件访问不到，找不到原因 ，能看看吗 ![image](https://user-images.githubusercontent.com/20351530/176634592-b37b3b19-ab39-492f-bcce-e48e419d36de.png)

进行了什么操作？如何启动项目的？

**Comment by fyl080801** [comment]
需要先运行build，构建出dist资源

**Comment by fyl080801** [comment]
没事了，看错了，最后正常了吧
